import type { Lesson, VocabularyEntry } from '../types';

const entry = (id: string, groupId: string, spanish: string, german: string[], kind: VocabularyEntry['kind']): VocabularyEntry => ({
  id, groupId, spanish, german, kind,
});

export const spanish02: Lesson = {
  id: 'spanish-02',
  subjectId: 'spanish',
  title: 'Tiere, Farben und mehr',
  subtitle: 'Weitere Wörter aus Unidad 1',
  sourceDate: '2026-09-12',
  groups: [
    { id: 'nomen', title: 'Tiere und Dinge' },
    { id: 'nachname', title: 'Nachname und Schreibweise' },
    { id: 'antworten', title: 'Antworten und Zahlen' },
    { id: 'farben', title: 'Farben' },
    { id: 'sehen', title: 'Sehen und Beschreiben' },
  ],
  entries: [
    entry('la-jirafa', 'nomen', 'la jirafa', ['die Giraffe'], 'phrase'),
    entry('el-koala', 'nomen', 'el koala', ['der Koala'], 'phrase'),
    entry('la-luna', 'nomen', 'la luna', ['der Mond'], 'phrase'),
    entry('la-mochila', 'nomen', 'la mochila', ['der Rucksack'], 'phrase'),
    entry('la-nube', 'nomen', 'la nube', ['die Wolke'], 'phrase'),
    entry('espana', 'nomen', 'España', ['Spanien'], 'word'),
    entry('la-oveja', 'nomen', 'la oveja', ['das Schaf'], 'phrase'),
    entry('el-perro', 'nomen', 'el perro', ['der Hund'], 'phrase'),
    entry('el-queso', 'nomen', 'el queso', ['der Käse'], 'phrase'),
    entry('la-rana', 'nomen', 'la rana', ['der Frosch'], 'phrase'),
    entry('el-sol', 'nomen', 'el sol', ['die Sonne'], 'phrase'),
    entry('el-tomate', 'nomen', 'el tomate', ['die Tomate'], 'phrase'),
    entry('uno', 'antworten', 'uno', ['eins'], 'word'),
    entry('la-vaca', 'nomen', 'la vaca', ['die Kuh'], 'phrase'),
    {
      ...entry('el-wifi', 'nomen', 'el wifi', ['das W-Lan'], 'phrase'),
      acceptedGerman: ['das WLAN', 'das W-LAN'],
    },
    entry('el-taxi', 'nomen', 'el taxi', ['das Taxi'], 'phrase'),
    entry('la-playa', 'nomen', 'la playa', ['der Strand'], 'phrase'),
    entry('el-zapato', 'nomen', 'el zapato', ['der Schuh'], 'phrase'),
    entry('cual-es-tu-apellido', 'nachname', '¿Cuál es tu apellido?', ['Wie heißt du mit Nachnamen?'], 'phrase'),
    entry('es', 'nachname', 'es', ['er ist', 'sie ist', 'es ist'], 'word'),
    {
      ...entry('el-apellido', 'nachname', 'el apellido', ['der Nachname'], 'phrase'),
      example: { spanish: 'Me llamo Julia y mi apellido es Wagner.', german: 'Ich heiße Julia und mit Nachnamen Wagner.' },
    },
    entry('como-se-escribe', 'nachname', '¿Cómo se escribe...?', ['Wie schreibt man ...?'], 'phrase'),
    entry('se-escribe', 'nachname', 'Se escribe...', ['Man schreibt ...', '... wird ... geschrieben.'], 'phrase'),
    {
      ...entry('con-dos-puntos', 'nachname', 'con dos puntos', ['mit Umlaut'], 'phrase'),
      example: { spanish: 'Müller se escribe con u con dos puntos.', german: 'Müller schreibt man mit u Umlaut.' },
    },
    entry('con-acento', 'nachname', 'con acento', ['mit Akzent'], 'phrase'),
    entry('el-animal', 'nomen', 'el animal', ['das Tier'], 'phrase'),
    entry('el-cocodrilo', 'nomen', 'el cocodrilo', ['das Krokodil'], 'phrase'),
    entry('el-delfin', 'nomen', 'el delfín', ['der Delfin'], 'phrase'),
    entry('el-leon', 'nomen', 'el león', ['der Löwe'], 'phrase'),
    entry('el-oso', 'nomen', 'el oso', ['der Bär'], 'phrase'),
    entry('el-pinguino', 'nomen', 'el pingüino', ['der Pinguin'], 'phrase'),
    entry('la-tortuga', 'nomen', 'la tortuga', ['die Schildkröte'], 'phrase'),
    entry('la-cebra', 'nomen', 'la cebra', ['das Zebra'], 'phrase'),
    entry('la-foto', 'nomen', 'la foto', ['das Foto'], 'phrase'),
    entry('si', 'antworten', 'sí', ['ja'], 'word'),
    {
      ...entry('no', 'antworten', 'no', ['nein', 'nicht', 'kein', 'keine'], 'word'),
      example: { spanish: '—¿Es España una isla?\n—No. No es una isla.', german: '– Ist Spanien eine Insel?\n– Nein. Es ist keine Insel.' },
    },
    {
      ...entry('el-numero', 'antworten', 'el número', ['die Nummer', 'die Anzahl', 'die Zahl'], 'phrase'),
      example: { spanish: 'Es la foto número uno.', german: 'Es ist das Foto eins.' },
    },
    entry('el-color', 'farben', 'el color', ['die Farbe'], 'phrase'),
    {
      ...entry('de-que-color', 'farben', '¿De qué color es/son...?', ['Welche Farbe hat/haben ...?'], 'phrase'),
      acceptedSpanish: ['¿De qué color es...?', '¿De qué color son...?'],
      acceptedGerman: ['Welche Farbe hat ...?', 'Welche Farbe haben ...?'],
    },
    {
      ...entry('de-color', 'farben', '... es/son de color ...', ['... hat/haben die Farbe ...'], 'phrase'),
      acceptedSpanish: ['... es de color ...', '... son de color ...'],
      acceptedGerman: ['... hat die Farbe ...', '... haben die Farbe ...'],
      example: { spanish: 'La tortuga es de color verde.', german: 'Die Schildkröte ist grün.' },
    },
    entry('marron', 'farben', 'marrón', ['braun'], 'word'),
    entry('verde', 'farben', 'verde', ['grün'], 'word'),
    entry('gris', 'farben', 'gris', ['grau'], 'word'),
    entry('blanco', 'farben', 'blanco', ['weiß'], 'word'),
    entry('rojo', 'farben', 'rojo', ['rot'], 'word'),
    entry('azul', 'farben', 'azul', ['blau'], 'word'),
    entry('amarillo', 'farben', 'amarillo', ['gelb'], 'word'),
    entry('rosa', 'farben', 'rosa', ['rosa'], 'word'),
    entry('naranja', 'farben', 'naranja', ['orange'], 'word'),
    entry('morado', 'farben', 'morado', ['lila', 'violett'], 'word'),
    entry('negro', 'farben', 'negro', ['schwarz'], 'word'),
    entry('veo', 'sehen', 'Veo.', ['Ich sehe.'], 'phrase'),
    entry('que-ves', 'sehen', '¿Qué ves?', ['Was siehst du?'], 'phrase'),
    {
      ...entry('que', 'sehen', '¿Qué...?', ['Was ...?'], 'phrase'),
      example: { spanish: '¿Qué es?', german: 'Was ist das?' },
    },
    {
      ...entry('la-cosita', 'sehen', 'la cosita', ['die (kleine) Sache'], 'phrase'),
      acceptedGerman: ['die Sache', 'die kleine Sache'],
    },
    entry('es-correcto', 'sehen', 'Es correcto.', ['Das ist richtig.'], 'phrase'),
    entry('no-es-correcto', 'sehen', 'No es correcto.', ['Das ist nicht richtig.'], 'phrase'),
  ],
};
